### PR TITLE
Validation|Model Specs

### PR DESCRIPTION
**Pull request by RileyManda**
I have completed implementing validations and model specs feature according to the[requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md): 🌱 

# Implementations:

### User model:
-Validation:User[name must not be blank]
-Validation:Post: PostsCounter must be an integer greater than or equal to zero.
-PostsCounter must be an integer greater than or equal to zero.

### Post model:
-Title must not be blank.
-Title must not exceed 250 characters.
-CommentsCounter must be an integer greater than or equal to zero.
-LikesCounter must be an integer greater than or equal to zero.
###
##  Model Specs

Implemented the following specs

<details>
<summary>Like</summary>

- should like existing post
- should not like a post without a user
</details>

<details>
<summary>Comment</summary>

- comment text should not be blank
- should return the comment text
- is valid with valid attributes
- is not valid without a post
</details>

<details>
<summary>User</summary>

- name must not be blank
- postsCounter must be an integer greater than or equal to zero
</details>

<details>
<summary>Post</summary>

- title must not be blank
- title must not exceed 250 characters.
- commentsCounter must be an integer greater than or equal to zero
- likesCounter must be an integer greater than or equal to zero
</details>

 In addition I have ensured the following general requirements:
 
### General requirements

> Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
> Made sure that I have used correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
> Made sure that I have documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
> Followed list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

Please kindly review my implementation.

Thank you 🙏🏻

### CODE REVIEW

**Review by DuaneDave — CHANGES_REQUESTED** [review]
Hi @RileyManda 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Validations are well set up
✔️ All models were tested

## Required Changes ♻️
- To make the documentation for this project more professional, I recommend that you add a License file to the project, such that when the License [link](https://github.com/RileyManda/blog-app/tree/feature/validations#-license-:~:text=ProjectIcon%3A%20Svgrepo-,%F0%9F%93%9D%20License,-(back%20to) is clicked, it links to an actual license and not a 404 page

_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by RileyManda** [comment]
I have added a licence to the project as requested by the reviewer.

# Implementations:

- Added licence to project

Please kindly review my implementation.

Thank You 🙏🏻

**Comment by RileyManda** [comment]
I have added a license to the project as requested by the reviewer.

## Implementations:

- Added [license](https://github.com/RileyManda/blog-app/pull/9/commits/b9bc525ea7411f8ee009bb817fbdb80f215d4eb5) to project readme file.

Please kindly review my implementation.

Thank You 🙏🏻

**Review by Gambit142 — APPROVED** [review]
Hi @RileyManda 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- Setup linters correctly ✔️ 
- Use Rspec as a testing library ✔️ 
- Wrote validations for models where necessary ✔️ 
- Wrote validation specs for models ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
